# Generated by Django 2.2.7 on 2019-11-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191120_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='updated_by',
            field=models.IntegerField(),
        ),
    ]
