# Generated by Django 2.2 on 2019-11-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20191122_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
    ]
