# Generated by Django 2.2.7 on 2019-11-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=6),
        ),
    ]
