# Generated by Django 2.2.7 on 2019-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20191124_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='operation',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='room',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
