# Generated by Django 2.2.7 on 2019-11-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_service_service_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Service_Group'),
        ),
    ]
