# Generated by Django 2.2.7 on 2019-11-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_delvery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delvery',
            new_name='Delivery',
        ),
    ]
