# Generated by Django 2.2.7 on 2019-11-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('birth_date', models.DateField(max_length=10)),
                ('address', models.CharField(choices=[('Banaadir', 'Banaadir'), ('Jubbada Dhexe', 'Jubbada Dhexe'), ('Jubbada Hoose', 'Jubbada Hoose'), ('Mudug', 'Mudug'), ('Hiiran', 'Hiiran'), ('Awdal', 'Awdal'), ('Bakool', 'Bakool'), ('Bari', 'Bari'), ('Baay', 'Baay'), ('Galgaduud', 'Galgaduud'), ('Gedo', 'Gedo'), ('Nugaal', 'Nugaal'), ('Sanaag', 'Sanaag'), ('Shabeellaha Hoose', 'Shabeellaha Hoose'), ('Shabeellaha Dhexe', 'Shabeellaha Dhee'), ('Sool', 'Sool'), ('Togdheer', 'Togdheer'), ('Woqooyi Galbeed', 'Woqooyi Galbeed')], default='Banaadir', max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Child', 'Child'), ('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=6)),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
