# Generated by Django 2.2.7 on 2019-12-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20191202_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Allergy & immunology', 'Allergy & immunology'), ('Anesthesiology', 'Anesthesiology'), ('Dermatology', 'Dermatology'), ('Diagnostic radiology', 'Diagnostic radiology'), ('Emergency medicine', 'Emergency medicine'), ('Family medicine', 'Family medicine'), ('Internal medicine', 'Internal medicine'), ('Medical genetics', 'Medical genetics'), ('Neurology', 'Neurology'), ('Nuclear medicine', 'Nuclear medicine'), ('Obstetrics and gynecology', 'Obstetrics and gynecology'), ('Ophthalmology', 'Ophthalmology'), ('Pathology', 'Pathology'), ('Pediatrics', 'Pediatrics'), ('Physical medicine & rehabilitation', 'Physical medicine & rehabilitation'), ('Preventive medicine', 'Preventive medicine'), ('Psychiatry', 'Psychiatry'), ('Radiation oncology', 'Radiation oncology'), ('Surgery', 'Surgery'), ('Urology', 'Urology')], default='Family medicine', max_length=100),
        ),
    ]
