# Generated by Django 2.2.7 on 2019-12-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_doctor_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnose', models.CharField(max_length=100, unique=True)),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheif_complain', models.CharField(max_length=400)),
                ('past_medical_history', models.CharField(choices=[('MD', 'MD'), ('HTN', 'HTN'), ('Cardiac', 'Cardiac'), ('Other', 'Other')], max_length=100)),
                ('other', models.CharField(blank=True, max_length=400, null=True)),
                ('past_surgical_history', models.CharField(max_length=300)),
                ('bp', models.CharField(max_length=10)),
                ('p', models.CharField(max_length=10)),
                ('temprature', models.CharField(max_length=10)),
                ('pso', models.CharField(max_length=10)),
                ('clinical_examination', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('diagnose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Diagnose')),
            ],
        ),
    ]
