# Generated by Django 2.2.7 on 2019-12-04 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_diagnose_surgeryhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryhistory',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ticket'),
            preserve_default=False,
        ),
    ]
