# Generated by Django 2.2.7 on 2019-12-04 07:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20191204_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeryhistory',
            name='past_medical_history',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MD', 'MD'), ('HTN', 'HTN'), ('Cardiac', 'Cardiac'), ('Other', 'Other')], max_length=20),
        ),
    ]
