# Generated by Django 2.2 on 2019-12-06 06:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20191204_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeryhistory',
            name='past_medical_history',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DM', 'DM'), ('HTN', 'HTN'), ('Cardiac', 'Cardiac'), ('Other', 'Other')], max_length=20),
        ),
    ]
