# Generated by Django 2.2 on 2019-12-06 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20191206_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Lab_Group')),
                ('lab_test', models.ManyToManyField(to='dashboard.Lab')),
            ],
        ),
    ]
