# Generated by Django 2.2.7 on 2019-12-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_labrequest_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ticket'),
        ),
    ]
