# Generated by Django 2.2.7 on 2019-12-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_auto_20191209_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labrequest',
            name='ticket',
        ),
    ]
