# Generated by Django 2.2.7 on 2019-12-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_remove_labrequest_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='ticket',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ticket'),
            preserve_default=False,
        ),
    ]
