# Generated by Django 2.2.7 on 2019-12-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_labrequest_myfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labrequest',
            name='myfield',
        ),
    ]
