# Generated by Django 2.2.7 on 2019-12-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20191209_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
    ]
