# Generated by Django 2.2.7 on 2019-12-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20191209_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labrequest',
            name='created',
        ),
        migrations.RemoveField(
            model_name='labrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labrequest',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='labrequest',
            name='updated_by',
        ),
    ]
