# Generated by Django 2.2.7 on 2019-12-09 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20191209_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labrequest',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
