# Generated by Django 2.2.7 on 2019-12-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20191209_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='examined',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='paid',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
